### ISSUE TITLE
Update allowed polcies

### ISSUE THREAD

**Issue by partharamanujam** [helmetjs/referrer-policy#1]
The referrer-policy allows for the following additional attributes:  
1. strict-origin 
2. strict-origin-when-cross-origin  

Please include above in allowed-list.

Refer: https://www.w3.org/TR/referrer-policy/#referrer-policies

**Comment by EvanHahn** [comment]
Would you like to try making a pull request? It'll involve adding some tests and adding it to the [list of supported policies](https://github.com/helmetjs/referrer-policy/blob/master/index.js#L2-L10).

If not, I can take a shot, but I won't get to it for a little while.

**Comment by partharamanujam** [comment]
Done; please check and let me know

**Comment by EvanHahn** [comment]
Will do! It'll probably be a couple of days before I can get to it, though.

Thanks for the PR!

**Comment by EvanHahn** [comment]
Forgot to close this issue after #2 was merged. Closing now.
